### ISSUE TITLE
Problems with the current guide

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/guide-testing-apps#1]
I am referencing: https://developer.enonic.com/guides/writing-unit-tests

Issues found in this repo:
* Old gradle wrapper distribution did not support Java 11 (See PR #2 )
* XP version was not the latest one (See PR #2 )
* Old gradle plugins did not work with new XP version (See PR #2 )
* Redundant dependency on junit 4.12 (See PR #2 )

Extra things that would be nice to have in the guide.
* For people unfamiliar with gradle that want to quickly checkout this project and run the test but don't know how, adding a simple section that says run `./gradlew clean test` to run the tests makes it clear how to do.
* Show people that there is a report generated that can be viewed at `./build/reports/tests/test/index.html` once tests are run.

**Comment by rymsha** [comment]
It was fixed AFAICT but docs were not published. @alansemenov we should publish it (probably after https://github.com/enonic/guide-testing-apps/pull/5)
